name: High vulns Snyk PR scan

on: pull_request

env:
  IMAGE_NAME: dwpdigital/hiverunner

jobs:
  docker-build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
